version: "3.9"

services:
  db:
    image: postgres:16
    container_name: memo_db
    restart: always
    environment:
      POSTGRES_USER: memo_db
      POSTGRES_PASSWORD: tanjoubi0622
      POSTGRES_DB: memo_db
    ports:
      - "5432:5432"
    volumes:
      - memo_db_data:/var/lib/postgresql/data

  api:
    build: ./api
    container_name: memo_api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://memo_db:tanjoubi0622@db:5432/memo_db?schema=public
      CORS_ORIGIN: http://3.107.229.153
      PORT: 3000

  web:
    build:
      context: ./web
      args:
        VITE_API_URL: http://3.107.229.153:3000
    container_name: memo_web
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  memo_db_data:
