export { createAuthUseCases } from './application/authUseCases';
export type { AuthUseCases } from './application/authUseCases';
export { ensureDemoUser } from './application/ensureDemoUser';
export { createBcryptPasswordHasher } from './infrastructure/passwordHasherBcrypt';
export { createJwtTokenService } from './infrastructure/tokenServiceJwt';
export { createUserRepositoryPrisma } from './infrastructure/userRepositoryPrisma';
export { createAuthMiddleware } from './presentation/http/authMiddleware';
export { createAuthRouter } from './presentation/http/authRouter';
export type { AuthenticatedRequest } from './presentation/http/authMiddleware';
export { isAuthenticatedRequest } from './presentation/http/authMiddleware';
