import {
  AD_CAMPAIGN_ACTION,
  BUYBACK_ACTION,
  CAPITAL_INCREASE_ACTION,
  COMPANY_ACTION_INITIAL_CHARGES,
  DEFAULT_MANAGEMENT_STAKE_SHARES,
  FACILITY_INVESTMENT_ACTION,
  INITIAL_FEINT_TOKENS,
  type GameState,
} from '../types';

export function createInitialGameState(): GameState {
  return {
    title: 'Price Battle',
    turn: 8,
    marketCondition: 'bull',
    victoryCondition: '最後に現金と自分レートの市場価値を合わせた値が高いプレイヤーの勝利',
    currentPlayer: 'player1',
    initialTotalAssets: 100000,
    rngSeed: 1,
    rngCursor: 0,
    forwardOrders: [],
    eventDeck: [],
    revealedEvents: [],
    speculationDelayActive: false,
    stocks: [
      {
        key: 'p1',
        name: 'プレイヤー1レート',
        basePrice: 1000000,
        currentPrice: 1000000,
        previousPrice: 1000000,
        bubbleUpper: 13000,
        bubbleLower: 7000,
        history: [1000000],
        shortInterest: 0,
        correlationNote: 'プレイヤー1側の価格対象',
        cpuPool: [],
      },
      {
        key: 'p2',
        name: 'プレイヤー2レート',
        basePrice: 1000000,
        currentPrice: 1000000,
        previousPrice: 1000000,
        bubbleUpper: 13000,
        bubbleLower: 7000,
        history: [1000000],
        shortInterest: 0,
        correlationNote: 'プレイヤー2側の価格対象',
        cpuPool: [],
      },
      {
        key: 'market',
        name: 'マーケット',
        basePrice: 1000000,
        currentPrice: 1000000,
        previousPrice: 1000000,
        bubbleUpper: 13000,
        bubbleLower: 7000,
        history: [1000000],
        shortInterest: 0,
        correlationNote: '共通マーケット',
        cpuPool: [],
      },
    ],
    players: [
      {
        id: 'player1',
        name: 'プレイヤー1',
        cash: 12800,
        companyFunds: 8400,
        managementStakeShares: DEFAULT_MANAGEMENT_STAKE_SHARES,
        startingOwnStockPrice: 1000000,
        holdings: {
          p1: { quantity: 0, avgPrice: 0 },
          p2: { quantity: 0, avgPrice: 0 },
          market: { quantity: 0, avgPrice: 0 },
        },
        shorts: {
          p1: { quantity: 0, avgPrice: 0 },
          p2: { quantity: 0, avgPrice: 0 },
          market: { quantity: 0, avgPrice: 0 },
        },
        positions: [],
        speculation: [],
        companyActionCharges: {
          [CAPITAL_INCREASE_ACTION]: COMPANY_ACTION_INITIAL_CHARGES,
          [AD_CAMPAIGN_ACTION]: COMPANY_ACTION_INITIAL_CHARGES,
          [BUYBACK_ACTION]: COMPANY_ACTION_INITIAL_CHARGES,
          [FACILITY_INVESTMENT_ACTION]: COMPANY_ACTION_INITIAL_CHARGES,
        },
        feintTokens: INITIAL_FEINT_TOKENS,
        recentCashChange: 350,
        recentNetChange: 620,
        marketBias: 0,
        lastSnapshotAssets: 0,
        lastSnapshotCash: 12800,
      },
      {
        id: 'player2',
        name: 'プレイヤー2',
        cash: 11900,
        companyFunds: 9100,
        managementStakeShares: DEFAULT_MANAGEMENT_STAKE_SHARES,
        startingOwnStockPrice: 1000000,
        holdings: {
          p1: { quantity: 0, avgPrice: 0 },
          p2: { quantity: 0, avgPrice: 0 },
          market: { quantity: 0, avgPrice: 0 },
        },
        shorts: {
          p1: { quantity: 0, avgPrice: 0 },
          p2: { quantity: 0, avgPrice: 0 },
          market: { quantity: 0, avgPrice: 0 },
        },
        positions: [],
        speculation: [],
        companyActionCharges: {
          [CAPITAL_INCREASE_ACTION]: COMPANY_ACTION_INITIAL_CHARGES,
          [AD_CAMPAIGN_ACTION]: COMPANY_ACTION_INITIAL_CHARGES,
          [BUYBACK_ACTION]: COMPANY_ACTION_INITIAL_CHARGES,
          [FACILITY_INVESTMENT_ACTION]: COMPANY_ACTION_INITIAL_CHARGES,
        },
        feintTokens: INITIAL_FEINT_TOKENS,
        recentCashChange: -220,
        recentNetChange: -410,
        marketBias: 0,
        lastSnapshotAssets: 0,
        lastSnapshotCash: 11900,
      },
    ],
    logs: [
      {
        id: 801,
        turn: 8,
        type: 'player',
        label: '上げる',
        message: 'プレイヤー1がプレイヤー1レートへ資金を入れ、価格が上がりました。',
        tone: 'up',
      },
      {
        id: 802,
        turn: 8,
        type: 'player',
        label: '下げる',
        message: 'プレイヤー2がマーケットを下げる方向へ動き、価格が下がりました。',
        tone: 'down',
      },
    ],
  };
}
