ALTER TABLE "Memos"
ADD COLUMN IF NOT EXISTS "orderIndex" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "Memos"
ADD COLUMN IF NOT EXISTS "width" INTEGER;

ALTER TABLE "Memos"
ADD COLUMN IF NOT EXISTS "height" INTEGER;
